markdown:       rdiscount
safe:           true
lsi:            false
highlighter:    pygments
permalink:      /:year/:month/:day/:title.html
author:			Taylor Steven (taylor.steven.wong@gmail.com)
title:          '泰来的永恒城堡'
url:            http://taylor-steven.github.io
description:    "我的成长日记"
feed:           /atom.xml
