markdown:       rdiscount
safe:           true
lsi:            false
highlighter:    pygments
permalink:      /:year/:month/:day/:title.html
author:			Taylor Steven (taylor.steven.wong@gmail.com)
title:          '泰来的博客'
site:
    title:          '泰来的博客'
url:            http://taylor-steven.github.io
description:    "泰来的博客"
feed:           /atom.xml
